# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='message_chanel_id',
        ),
    ]
