# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0002_remove_team_message_chanel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermessage',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='askmessage',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
