# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 12:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=20)),
                ('ts', models.CharField(max_length=40)),
                ('text', models.TextField()),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AskMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('author_id', models.CharField(max_length=20)),
                ('ts', models.CharField(max_length=40)),
                ('channel', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('is_answered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('team_id', models.CharField(max_length=20)),
                ('message_chanel_id', models.CharField(max_length=100, null=True)),
                ('message_chanel_name', models.CharField(max_length=100, null=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_of_teams', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='member_of_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='askmessage',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ask_messages', to='ask_leave_bot.Team'),
        ),
        migrations.AddField(
            model_name='answermessage',
            name='ask_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_messages', to='ask_leave_bot.AskMessage'),
        ),
    ]
