# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=20)),
                ('ts', models.CharField(max_length=40)),
                ('text', models.TextField()),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AskMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('author_id', models.CharField(max_length=20)),
                ('ts', models.CharField(max_length=40)),
                ('channel', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('is_answered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('team_id', models.CharField(max_length=20)),
                ('bot_user_id', models.CharField(max_length=20)),
                ('bot_access_token', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='askmessage',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ask_messages', to='ask_leave_bot.Team'),
        ),
        migrations.AddField(
            model_name='answermessage',
            name='ask_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_messages', to='ask_leave_bot.AskMessage'),
        ),
    ]
