# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 08:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ask_leave_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='moderators',
            field=models.ManyToManyField(null=True, related_name='moderator_of_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
