# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 08:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_leave_bot', '0002_team_moderators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='moderators',
            field=models.ManyToManyField(related_name='moderator_of_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
