# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 10:04
from __future__ import unicode_literals

import auth_token_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManyDevicesExpiratoryToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.Token')),
                ('used_devices', models.PositiveSmallIntegerField(default=0)),
                ('expiration_date', models.DateTimeField(default=auth_token_app.models.get_now_plus_1_day)),
            ],
            bases=('authtoken.token',),
        ),
    ]
