# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_token_app', '0002_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='user_agent',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
