# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_token_app', '0003_auto_20171221_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manydevicesexpiratorytoken',
            name='used_devices',
        ),
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='auth_token_app.ManyDevicesExpiratoryToken'),
        ),
    ]
